### PR TITLE
Update data.js

### PR DESCRIPTION
**Pull request by Gupta-Suruchi**
Updated list of Indian & Pakistani Rappers in data.js

### CODE REVIEW

**Comment by Gupta-Suruchi** [comment]
Hi @ashishalf, Can you please take a look & merge my pull request.

**Comment by heyashishsaini** [comment]
hey, @protonpluss, please add square-size images and add at least 10 artists.

**Comment by heyashishsaini** [comment]
Seedhe Maut is already added

**Comment by heyashishsaini** [comment]
and artists added on the top

**Comment by heyashishsaini** [comment]
One more thing, when you write country name that will be in lower-case, I already mentioned it and only use "indian" or "pakistani".

**Comment by Gupta-Suruchi** [comment]
Got your Point Thanks!

**Pull request merged**
